version: '3.7'

services: 
  db:
    image: mariadb:10.6.5-focal
    ports:
      - '3306:3306'
    container_name: 'dtc_dbdocker '
    restart: always
    command: ['--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    environment:
      MYSQL_DATABASE: "dtc"
      MYSQL_USER: "dtc-db-user"
      MYSQL_PASSWORD: "dtc-db-password"
      MYSQL_ROOT_PASSWORD: "docker-db-root-password"

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: dtc_web
    restart: always
    volumes:
      - .:/app
    ports: 
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
